
version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server  
    ports:
      - "12345:12345"
    networks:
      - reservas_net

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    depends_on:
      - server
    networks:
      - reservas_net

networks:
  reservas_net:
    driver: bridge
